# Generated by Django 5.0.3 on 2024-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_info_alter_user_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creation_time',
            new_name='created_at',
        ),
    ]
