# Generated by Django 5.0.3 on 2024-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_creation_time_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.CharField(max_length=200),
        ),
    ]
