# Generated by Django 5.0.3 on 2024-04-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_created_at_user_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
