# Generated by Django 5.0.3 on 2024-04-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_info',
            field=models.TextField(blank=True),
        ),
    ]
